<a href="https://colab.research.google.com/github/TIMEdilation584/JP_Loksatta_moving_hearts/blob/master/18_02_22_My_independent_work_on_lists_of_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
const_names = ['Alex', 'Bob', 'Johny', 'Atta']


const obj = Object.assign({}, names)


console.log(obj)



SyntaxError: ignored

In [ ]:

# import module
import numpy as np
  
# create array
print("\nArray:")
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr)
print(type(arr))
  
# apply method
lis = arr.tolist()
  
# display list
print("\nList:")
print(lis)
print(type(lis))


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>

List:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [ ]:
 
list1=[['a'],[1,2,3]]
list2=[['b'],[2,4,5]]
list3 = [['c'],[3,7,8]]
listoflists= []
listoflists.append(list1)
listoflists.append(list2)
listoflists.append(list3)
print("List of Lists:",listoflists)

List of Lists: [[['a'], [1, 2, 3]], [['b'], [2, 4, 5]], [['c'], [3, 7, 8]]]


In [ ]:
listoflists[1:0]

[]

In [ ]:
for a in listoflists:
    print(item)

[['b'], [2, 4, 5]]
[['b'], [2, 4, 5]]


In [ ]:
for i in listoflists:
  print("list",i,"elements")
  for j in i:
    print(j)

list [['a'], [1, 2, 3]] elements
['a']
[1, 2, 3]
list [['b'], [2, 4, 5]] elements
['b']
[2, 4, 5]
list [['c'], [3, 7, 8]] elements
['c']
[3, 7, 8]


In [ ]:
listoflists[1][0]

[['b']]

In [ ]:
mylist4 = []
for solo in listoflists:
   for j in solo[0]:
    mylist4.append(solo[0])

print(mylist4)


[['a'], ['b'], ['c']]


In [ ]:
mylist5 = []
for solo in listoflists:
   for j in solo[1]:
    mylist5.append(solo[1])

print(mylist5)


[[1, 2, 3], [1, 2, 3], [1, 2, 3], [2, 4, 5], [2, 4, 5], [2, 4, 5], [3, 7, 8], [3, 7, 8], [3, 7, 8]]


In [ ]:

patients = [ ['Milos', 'Jones', 48, 'male', 'smoker', 210], 
             ['Delia', 'Chan', 39, 'female', 'non-smoker', 170], 
             ['Denise', 'Ross', 62, 'female', 'non-smoker', 150] ]

female_patients = []
for solo_patient in patients:
    if solo_patient[3] == 'female':
        female_patients.append(solo_patient[1])

print(female_patients)

['Chan', 'Ross']
